src/SmsWebSender/Controllers/SmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SmsWebSender.Models;
using SmsWebSender.ServiceInterfaces;
using SmsWebSender.ViewModels.Sms;

namespace SmsWebSender.Controllers
{
    [Route("smsApp")]
    public class SmsController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        private readonly ISmsService _smsService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailService _emailService;
        private readonly IConfiguration _configuration;
        private readonly ApplicationDbContext _context;
        private const int IcelandicAreaCode = 354;

        public SmsController(IAppointmentService appointmentService,
            ISmsService smsService, 
            UserManager<ApplicationUser> userManager,
            IEmailService emailService,
            IConfiguration configuration,
            ApplicationDbContext context)
        {
            _appointmentService = appointmentService;
            _smsService = smsService;
            _userManager = userManager;
            _emailService = emailService;
            _configuration = configuration;
            _context = context;
        }

        [Authorize]
        [Route("")]
        public async Task<IActionResult> Index()
        {
            var userSending = await _userManager.FindByIdAsync(_userManager.GetUserId(User));

            var vm = new SmsViewModel
            {
                SenderName = userSending.SendSmsName,
                CompanyName = userSending.CompanyName,
                SmsTemplate = userSending.SmsTemplate
            };
            return View(vm);
        }

        [Authorize]
        [Route("List")]
        public IActionResult List()
        {
            var messages = _smsService.GetMessages();
            return View(messages);
        }

        [Authorize]
        [Route("MessageLinesBlocks")]
        public async Task<JsonResult> MessageLinesBlocks(DateTime date)
        {
            var user = await _userManager.FindByIdAsync(_userManager.GetUserId(User));
            var messageLinesBlocks = GetMessageLineBlocks(date, _appointmentService, user, false, _emailService);

            if (messageLinesBlocks == null)
            {
                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return new JsonResult("Error getting message data");
            }

            return new JsonResult(messageLinesBlocks);
        }

        internal static List<MessageLinesBlock> GetMessageLineBlocks(DateTime date, IAppointmentService appointmentService, ApplicationUser user, bool onlyIncludeShouldSendLines, IEmailService emailService)
        {
            List<Appointment> appointmentsForDay;
            try
            {
                appointmentsForDay = appointmentService.AppointmentsForDay(date);
            }
            catch (Exception ex)
            {
                emailService.SendEmailAsync("gudbjorn.einarsson@gmail.com", "SMS ERROR", $"Villa við að ná í bókanir fyrir daginn. Villuskilaboð: {ex.Message}", "hyldypi@hyldypi.is", "Hyldýpi");
                return null;
            }
            var messageLinesBlocks = new List<MessageLinesBlock>();

            foreach (var appointment in appointmentsForDay)
            {
                var messageLine = new MessageLine(user.SmsTemplate, appointment.StartTimeOfAppointment,
                    appointment.GsmNumber.ToString())
                {
                    Name = appointment.ClientName,
                    CalendarId = appointment.CalendarId,
                };

                if (onlyIncludeShouldSendLines && !messageLine.ShouldBeSentTo)
                {
                    continue;
                }

                var block = messageLinesBlocks.FirstOrDefault(mlb => mlb.EmployeeName == appointment.EmployeeName);
                if (block == null)
                {
                    block = new MessageLinesBlock { EmployeeName = appointment.EmployeeName };
                    messageLinesBlocks.Add(block);
                }

                block.MessageLines.Add(messageLine);
            }

            return messageLinesBlocks;
        }

        [HttpPost]
        [Authorize]
        [Route("Send")]
        public async Task Send([FromBody]List<MessageLinesBlock> messageLinesBlocks)
        {
            var user = await _userManager.FindByIdAsync(_userManager.GetUserId(User));
            SendBatch(messageLinesBlocks, _smsService, _emailService, user, _configuration, DateTime.MinValue);
        }

        /// <summary>
        /// Sends a batch of sms messages
        /// </summary>
        /// <param name="messageLinesBlocks">Message to send</param>
        /// <param name="smsService">Sms service</param>
        /// <param name="emailService">Email service</param>
        /// <param name="sendingUser">User we are sending for</param>
        /// <param name="configuration">System configurations</param>
        /// <param name="reminderDay">The day we are reminding clients about</param>
        /// <returns></returns>
        internal static void SendBatch(List<MessageLinesBlock> messageLinesBlocks, ISmsService smsService, IEmailService emailService, ApplicationUser sendingUser, IConfiguration configuration, DateTime reminderDay)
        {
            var messageLinesToSend = new List<MessageLine>();
            foreach (var block in messageLinesBlocks)
            {
                messageLinesToSend.AddRange(block.MessageLines.Where(line => line.ShouldBeSentTo));
            }

            var messages = new List<SmsMessage>();
            foreach (var messageLine in messageLinesToSend)
            {
                string to = $"+{IcelandicAreaCode}{messageLine.Number}";
                messages.Add(new SmsMessage { To = to, From = sendingUser.SendSmsName, Body = messageLine.Body });
            }

            if (!messages.Any()) return;

            smsService.SendBatch(messages, configuration["smsWebSenderCallbackUrl"]);

            if (sendingUser.SendSmsConfirmationToUser)
            {
                SendConfirmationSms(sendingUser, messages, smsService, reminderDay);

                // DEBUG
                // Also send to me so I can keep track of things
                emailService.SendEmailAsync("gudbjorn.einarsson@gmail.com", "Confirmation email", $"Sendi {messages.Count} skilaboð á {sendingUser.UserName}", "hyldypi@hyldypi.is", "Hyldýpi");
            }
        }

        /// <summary>
        /// Send confirmation sms to user that sms messagse have been sent on his behalf
        /// </summary>
        /// <param name="user">User whos sms message where sent</param>
        /// <param name="messagesToSend">The messages that were sent</param>
        /// <param name="smsService">Sms service</param>
        /// <param name="reminderDay">The date that clients where reminded about</param>
        private static void SendConfirmationSms(ApplicationUser user, List<SmsMessage> messagesToSend, ISmsService smsService, DateTime reminderDay)
        {
            var message = new SmsMessage
            {
                To = $"+{IcelandicAreaCode}{user.UsersGsmNumber}",
                From = "Hyldypi",
                Body = $"Vorum ad senda {messagesToSend.Count} sms fyrir thig fyrir {reminderDay.ToString("dd.MM")}. Vid latum thig vita ef einhver theirra komast ekki til skila." 
            };

            smsService.SendMessage(message, "");
            
        }

        [Route("Test")]
        [HttpGet]
        public IActionResult Test()
        {
            return View();
        }

        [Authorize]
        [Route("Test")]
        [HttpPost]
        public void Test(SmsWebSender.Models.SmsMessage vm)
        {
            _smsService.SendMessage(vm, _configuration["smsWebSenderCallbackUrl"]);
        }

        [Route("SmsCallback")]
        [HttpPost]
        public void SmsCallback(string SmsStatus, string From, string To)
        {
            // Only wish to alert the user of an unsuccessful status 
            if (SmsStatus != "undelivered" && SmsStatus != "failed")
            {
                return;
            }

            var user = _context.Users.FirstOrDefault(u => u.SendSmsName == From);
            if (user == null)
            {
                return;
            }

            string errorMessage = $"Ekki tokst a senda sms i numerid {To}";
            _smsService.SendMessage(new SmsMessage { From = "Hyldypi", To = $"+{IcelandicAreaCode}{user.UsersGsmNumber}", Body = errorMessage }, "");

            // Also send to me so I can keep track of things
            
                _emailService.SendEmailAsync("gudbjorn.einarsson@gmail.com", "Sms sending mistókst", errorMessage, "hyldypi@hyldypi.is",
                        "Hyldýpi");
        }

        [Route("SmsHourCallback")]
        [HttpPost]
        public void SmsHourCallback(int hour)
        {
            _emailService.SendEmailAsync(
                "gudbjorn.einarsson@gmail.com", 
                "Sms hour callback", 
                $"Var sent kl {hour}. Prófa hvort það virki að pinga síðuna frá einhverju random service. Ætla svo að bæta við parameters sem tekur inn kl hvað fyrirspurnin var gerð (og eitthvað security check líka)", 
                "hyldypi@hyldypi.is",
                "Hyldýpi");
        }

        [Route("TestEmailSending")]
        public void TestEmailSending(string SmsStatus, string From, string To)
        {
            _emailService.SendEmailAsync("gudbjorn.einarsson@gmail.com", "SMS test mail",
                    $"SmsStatus: {SmsStatus}, From: {From}, To: {To}", "hyldypi@hyldypi.is", "Hyldýpi");
        }

    }
}

src/SmsWebSender/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@using SmsWebSender.Models
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sms þjónustan</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/bootstrap-theme.css"/>
            <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
            <link rel="stylesheet" href="~/css/bootstrap-theme.min.css"/>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css"
                  asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">Sms áminningar</a>
                </div>
                <div class="navbar-collapse collapse">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="nav navbar-nav">
                            <li><a asp-controller="Sms" asp-action="List"><i class="fa fa-list"></i> Skilaboð</a></li>
                            @*<li><a asp-controller="Sms" asp-action="Index"><i class="fa fa-send"></i> Senda skilaboð</a></li>*@
                            <li><a asp-controller="Account" asp-action="Settings"><i class="fa fa-cog"></i> Stillingar</a></li>
                        </ul>
                    }
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <div class="footer navbar-fixed-bottom text-center">
                <hr />
                <h4 class="text-muted">Sms áminningar</h4>
            </div>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>